

---

- hosts: localhost
  tasks:
  - name: create rds_instance
    rds_instance:
      engine: postgres
      db_instance_identifier: postgres-db-instance
      instance_type: db.t2.small
      password: "asasasaeight"
      aws_access_key: 
      aws_secret_key: 
      state: present
      region: us-east-1
      username: "asdasdas"
      allocated_storage: 10
      tags:
         name: verintmyansiblerds
         type: example

- hosts: localhost
  tasks:
  - name: create S3 bucket
    s3_bucket:
      name: verintmyansiblebucket
      aws_access_key: 
      aws_secret_key: 
      #policy: "{{ lookup( 'file','my_bucket_policy.json' )}}"
      state: present
      region: us-east-1
      versioning: no
      tags:
         name: verintmyansiblebucket
         type: example